### ISSUE TITLE
small 0.10 fix

### ISSUE THREAD

**Issue by moebiussurfing** [NickHardeman/ofxCameraAnaglyph#2]
line 117 at ofxCameraAnaglyph.cpp

//    ofVec3f r = getSideDir().getNormalized() * (eyeSeparation/3.f);
	glm::vec3 n = glm::normalize(getSideDir());
	auto r = n * (eyeSeparation/3.f);

**Comment by NickHardeman** [comment]
Thank you. Can you send a PR so I can merge it in?

**Comment by NickHardeman** [comment]
Solved with PR. :)
